animals:
  avestruz:
    tags:
    - ave
  ballena:
    tags:
    - mamifero
    - vive en el mar
    - grande
  caballito de mar:
    tags:
    - pez
    - "peque\xF1o"
  caballo:
    tags:
    - cola larga
    - mamifero
    - domestico
  cabra:
    tags:
    - mamifero
    - bala
    - rumiante
    - cuernos
    - da leche
    - domestico
  cangrejo:
    tags:
    - crustaceo
    - pinzas
    - camina de lado
  caracol:
    tags:
    - molusco
    - caparazon
  cebra:
    tags:
    - cola larga
    - mamifero
    - rayas
    - herbivoro
  cerdo:
    tags:
    - mamifero
    - domestico
  cocodrilo:
    tags:
    - patas
    - reptil
  conejo:
    tags:
    - mamifero
    - orejas largas
  delfin:
    tags:
    - mamifero
    - vive en el mar
  gamba:
    tags:
    - crustaceo
  gato:
    tags:
    - mamifero
    - maulla
    - cola larga
    - felino
    - domestico
    - "peque\xF1o"
  hormiga:
    tags:
    - insecto
  humano:
    tags:
    - mamifero
    - bipedo
  jirafa:
    tags:
    - cola larga
    - mamifero
    - cuello largo
  koala:
    tags:
    - mamifero
    - trepa
  langosta:
    tags:
    - crustaceo
    - grande
  leon:
    tags:
    - mamifero
    - cola larga
    - felino
    - melena
    - carnivoro
  mariposa:
    tags:
    - alas
    - insecto
  mono:
    tags:
    - cola larga
    - mamifero
    - trepa
  ornitorrinco:
    tags:
    - mamifero
    - pico
  oveja:
    tags:
    - mamifero
    - bala
    - rumiante
    - lana
    - domestico
  pajaro carpintero:
    tags:
    - ave
    - vuela
  pato:
    tags:
    - nada
    - ave
    - pico
    - vuela
  perro:
    tags:
    - mamifero
    - domestico
    - ladra
  rana:
    tags:
    - anfibio
  raton:
    tags:
    - cola larga
    - mamifero
    - "peque\xF1o"
  rinoceronte:
    tags:
    - mamifero
    - cuernos
  salamandra:
    tags:
    - anfibio
    - cola
  serpiente:
    tags:
    - reptil
  tiburon:
    tags:
    - pez
  tigre:
    tags:
    - mamifero
    - cola larga
    - felino
    - rayas
    - carnivoro
  tortuga:
    tags:
    - patas
    - caparazon
    - reptil
  vaca:
    tags:
    - mamifero
    - muge
    - cola larga
    - rumiante
    - cuernos
    - da leche
    - domestico
tags:
- mamifero
- crustaceo
- camina de lado
- melena
- anfibio
- pico
- grande
- rayas
- herbivoro
- carnivoro
- vive en el mar
- reptil
- cuello largo
- ladra
- "peque\xF1o"
- maulla
- felino
- pinzas
- pez
- ave
- lana
- bala
- cuernos
- muge
- rumiante
- cola larga
- domestico
- vuela
- molusco
- insecto
- bipedo
- patas
- orejas largas
- cola
- nada
- trepa
- caparazon
- alas
