animals:
  avestruz:
    tags:
    - ave
  ballena:
    tags:
    - grande
    - mamifero
    - vive en el mar
  caballito de mar:
    tags:
    - "peque\xF1o"
    - pez
  caballo:
    tags:
    - domestico
    - mamifero
    - cola larga
  cabra:
    tags:
    - rumiante
    - mamifero
    - da leche
    - domestico
    - bala
    - cuernos
  cangrejo:
    tags:
    - crustaceo
    - camina de lado
    - pinzas
  canguro:
    tags:
    - bolsa marsupial
    - mamifero
    - cola larga
  caracol:
    tags:
    - molusco
    - caparazon
  cebra:
    tags:
    - rayas
    - mamifero
    - herbivoro
    - cola larga
  cerdo:
    tags:
    - domestico
    - mamifero
  cocodrilo:
    tags:
    - reptil
    - patas
  conejo:
    tags:
    - orejas largas
    - mamifero
  delfin:
    tags:
    - mamifero
    - vive en el mar
  gamba:
    tags:
    - crustaceo
  gato:
    tags:
    - mamifero
    - "peque\xF1o"
    - domestico
    - maulla
    - felino
    - cola larga
  hormiga:
    tags:
    - insecto
  humano:
    tags:
    - bipedo
    - mamifero
  jirafa:
    tags:
    - cuello largo
    - mamifero
    - cola larga
  koala:
    tags:
    - trepa
    - mamifero
  lagartija:
    tags:
    - reptil
    - "peque\xF1o"
    - patas
  langosta:
    tags:
    - crustaceo
    - grande
  leon:
    tags:
    - mamifero
    - melena
    - felino
    - carnivoro
    - cola larga
  mariposa:
    tags:
    - alas
    - insecto
  mono:
    tags:
    - trepa
    - mamifero
    - cola larga
  ornitorrinco:
    tags:
    - pico
    - mamifero
  oveja:
    tags:
    - rumiante
    - mamifero
    - lana
    - domestico
    - bala
  pajaro carpintero:
    tags:
    - vuela
    - ave
  pato:
    tags:
    - vuela
    - pico
    - nada
    - ave
  pelicano:
    tags:
    - vuela
    - nada
    - bolsa pico
    - ave
  perro:
    tags:
    - domestico
    - mamifero
    - ladra
  rana:
    tags:
    - anfibio
  raton:
    tags:
    - "peque\xF1o"
    - mamifero
    - cola larga
  rinoceronte:
    tags:
    - mamifero
    - cuernos
  salamandra:
    tags:
    - anfibio
    - cola
  serpiente:
    tags:
    - reptil
  tiburon:
    tags:
    - pez
  tigre:
    tags:
    - mamifero
    - rayas
    - felino
    - carnivoro
    - cola larga
  tortuga:
    tags:
    - reptil
    - patas
    - caparazon
  vaca:
    tags:
    - rumiante
    - mamifero
    - da leche
    - domestico
    - muge
    - cuernos
    - cola larga
tags:
- mamifero
- crustaceo
- camina de lado
- melena
- anfibio
- pico
- grande
- rayas
- herbivoro
- carnivoro
- vive en el mar
- reptil
- cuello largo
- ladra
- "peque\xF1o"
- maulla
- felino
- pinzas
- pez
- ave
- lana
- bala
- cuernos
- muge
- rumiante
- cola larga
- domestico
- vuela
- molusco
- insecto
- bipedo
- patas
- orejas largas
- cola
- nada
- trepa
- caparazon
- alas
- da leche
- bolsa pico
- bolsa marsupial
