# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\phorn\Documents\Code\anikator\gui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(755, 279)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(10, 65, 221, 31))
        self.output_label.setFrameShape(QtWidgets.QFrame.Box)
        self.output_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_label.setObjectName("output_label")
        self.si = QtWidgets.QPushButton(self.centralwidget)
        self.si.setGeometry(QtCore.QRect(240, 70, 31, 28))
        self.si.setObjectName("si")
        self.no = QtWidgets.QPushButton(self.centralwidget)
        self.no.setGeometry(QtCore.QRect(280, 70, 31, 28))
        self.no.setObjectName("no")
        self.candidates_label = QtWidgets.QLabel(self.centralwidget)
        self.candidates_label.setGeometry(QtCore.QRect(440, 50, 71, 16))
        self.candidates_label.setObjectName("candidates_label")
        self.candidates = QtWidgets.QLineEdit(self.centralwidget)
        self.candidates.setGeometry(QtCore.QRect(420, 70, 113, 22))
        self.candidates.setObjectName("candidates")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 755, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.output_label.setText(_translate("MainWindow", "---"))
        self.si.setText(_translate("MainWindow", "Si"))
        self.no.setText(_translate("MainWindow", "No"))
        self.candidates_label.setText(_translate("MainWindow", "Candidates"))
